framework:
    default_locale: '%env(APP_DEFAULT_LOCALE)%'
    enabled_locales: ['en', 'fr']
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - '%env(APP_DEFAULT_LOCALE)%'
