<?php

namespace Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20200712191326 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        $this->addSql('CREATE SEQUENCE subscriptions_logs_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE users_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE projects_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE website_posts_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE website_pages_categories_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE website_pages_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE website_posts_categories_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE website_documents_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE registrations_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE organizations_members_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE domains_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE organizations_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE uploads_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE community_tags_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE community_emailing_campaigns_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE community_emailing_campaigns_messages_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE community_contacts_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE subscriptions_logs (id BIGINT NOT NULL, organization_id BIGINT NOT NULL, message VARCHAR(50) NOT NULL, context JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_27FC727932C8A3DE ON subscriptions_logs (organization_id)');
        $this->addSql('CREATE TABLE users (id BIGINT NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, email VARCHAR(180) NOT NULL, is_admin BOOLEAN NOT NULL, password VARCHAR(250) NOT NULL, two_factor_auth_secret VARCHAR(64) DEFAULT NULL, two_factor_enabled BOOLEAN DEFAULT NULL, two_factor_backup_codes TEXT DEFAULT NULL, picture VARCHAR(64) DEFAULT NULL, locale VARCHAR(10) NOT NULL, secret_reset_password VARCHAR(64) DEFAULT NULL, due_date_reset_password TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, notification_settings JSON DEFAULT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9D17F50A6 ON users (uuid)');
        $this->addSql('COMMENT ON COLUMN users.two_factor_backup_codes IS \'(DC2Type:simple_array)\'');
        $this->addSql('COMMENT ON COLUMN users.due_date_reset_password IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN users.uuid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE projects (id BIGINT NOT NULL, organization_id BIGINT NOT NULL, root_domain_id BIGINT NOT NULL, appearance_logo_dark_id BIGINT DEFAULT NULL, appearance_logo_white_id BIGINT DEFAULT NULL, appearance_icon_id BIGINT DEFAULT NULL, name VARCHAR(60) NOT NULL, api_token VARCHAR(64) NOT NULL, modules TEXT NOT NULL, tools TEXT NOT NULL, sub_domain VARCHAR(150) DEFAULT NULL, appearance_primary VARCHAR(10) NOT NULL, appearance_secondary VARCHAR(10) NOT NULL, appearance_third VARCHAR(10) NOT NULL, website_locale VARCHAR(10) NOT NULL, website_custom_frontend BOOLEAN NOT NULL, social_email VARCHAR(150) DEFAULT NULL, social_facebook VARCHAR(150) DEFAULT NULL, social_twitter VARCHAR(150) DEFAULT NULL, social_instagram VARCHAR(150) DEFAULT NULL, social_linked_in VARCHAR(150) DEFAULT NULL, social_youtube VARCHAR(150) DEFAULT NULL, social_medium VARCHAR(150) DEFAULT NULL, social_telegram VARCHAR(32) DEFAULT NULL, legal_gdpr_name VARCHAR(100) DEFAULT NULL, legal_gdpr_email VARCHAR(100) DEFAULT NULL, legal_gdpr_address VARCHAR(200) DEFAULT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5C93B3A47BA2F5EB ON projects (api_token)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5C93B3A4D17F50A6 ON projects (uuid)');
        $this->addSql('CREATE INDEX IDX_5C93B3A432C8A3DE ON projects (organization_id)');
        $this->addSql('CREATE INDEX IDX_5C93B3A4584D14C2 ON projects (root_domain_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5C93B3A459FBCC09 ON projects (appearance_logo_dark_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5C93B3A478B771E ON projects (appearance_logo_white_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5C93B3A4B6319F89 ON projects (appearance_icon_id)');
        $this->addSql('COMMENT ON COLUMN projects.modules IS \'(DC2Type:simple_array)\'');
        $this->addSql('COMMENT ON COLUMN projects.tools IS \'(DC2Type:simple_array)\'');
        $this->addSql('COMMENT ON COLUMN projects.uuid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE projects_areas (project_id BIGINT NOT NULL, area_id BIGINT NOT NULL, PRIMARY KEY(project_id, area_id))');
        $this->addSql('CREATE INDEX IDX_CD31E662166D1F9C ON projects_areas (project_id)');
        $this->addSql('CREATE INDEX IDX_CD31E662BD0F409C ON projects_areas (area_id)');
        $this->addSql('CREATE TABLE website_posts (id BIGINT NOT NULL, image_id BIGINT DEFAULT NULL, project_id BIGINT NOT NULL, title VARCHAR(100) NOT NULL, slug VARCHAR(100) NOT NULL, description VARCHAR(150) DEFAULT NULL, quote VARCHAR(100) DEFAULT NULL, content TEXT NOT NULL, video VARCHAR(150) DEFAULT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DF370A36D17F50A6 ON website_posts (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DF370A363DA5256D ON website_posts (image_id)');
        $this->addSql('CREATE INDEX IDX_DF370A36166D1F9C ON website_posts (project_id)');
        $this->addSql('COMMENT ON COLUMN website_posts.uuid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE website_posts_posts_categories (post_id BIGINT NOT NULL, post_category_id BIGINT NOT NULL, PRIMARY KEY(post_id, post_category_id))');
        $this->addSql('CREATE INDEX IDX_CE3D47134B89032C ON website_posts_posts_categories (post_id)');
        $this->addSql('CREATE INDEX IDX_CE3D4713FE0617CD ON website_posts_posts_categories (post_category_id)');
        $this->addSql('CREATE TABLE website_pages_categories (id BIGINT NOT NULL, project_id BIGINT NOT NULL, name VARCHAR(40) NOT NULL, slug VARCHAR(50) NOT NULL, weight INT NOT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E0D4BA70D17F50A6 ON website_pages_categories (uuid)');
        $this->addSql('CREATE INDEX IDX_E0D4BA70166D1F9C ON website_pages_categories (project_id)');
        $this->addSql('COMMENT ON COLUMN website_pages_categories.uuid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE website_pages (id BIGINT NOT NULL, image_id BIGINT DEFAULT NULL, project_id BIGINT NOT NULL, title VARCHAR(100) NOT NULL, slug VARCHAR(100) NOT NULL, description VARCHAR(150) DEFAULT NULL, content TEXT NOT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_771E55B9D17F50A6 ON website_pages (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_771E55B93DA5256D ON website_pages (image_id)');
        $this->addSql('CREATE INDEX IDX_771E55B9166D1F9C ON website_pages (project_id)');
        $this->addSql('COMMENT ON COLUMN website_pages.uuid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE website_pages_pages_categories (page_id BIGINT NOT NULL, page_category_id BIGINT NOT NULL, PRIMARY KEY(page_id, page_category_id))');
        $this->addSql('CREATE INDEX IDX_8C8564D0C4663E4 ON website_pages_pages_categories (page_id)');
        $this->addSql('CREATE INDEX IDX_8C8564D05FAC390 ON website_pages_pages_categories (page_category_id)');
        $this->addSql('CREATE TABLE website_posts_categories (id BIGINT NOT NULL, project_id BIGINT NOT NULL, name VARCHAR(40) NOT NULL, slug VARCHAR(50) NOT NULL, weight INT NOT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1B286E2DD17F50A6 ON website_posts_categories (uuid)');
        $this->addSql('CREATE INDEX IDX_1B286E2D166D1F9C ON website_posts_categories (project_id)');
        $this->addSql('COMMENT ON COLUMN website_posts_categories.uuid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE website_documents (id BIGINT NOT NULL, file_id BIGINT DEFAULT NULL, project_id BIGINT NOT NULL, name VARCHAR(100) NOT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_31689A5CD17F50A6 ON website_documents (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_31689A5C93CB796C ON website_documents (file_id)');
        $this->addSql('CREATE INDEX IDX_31689A5C166D1F9C ON website_documents (project_id)');
        $this->addSql('COMMENT ON COLUMN website_documents.uuid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE registrations (id BIGINT NOT NULL, organization_id BIGINT DEFAULT NULL, email VARCHAR(180) NOT NULL, token VARCHAR(64) NOT NULL, is_admin BOOLEAN DEFAULT NULL, projects_permissions JSON DEFAULT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_53DE51E75F37A13B ON registrations (token)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_53DE51E7D17F50A6 ON registrations (uuid)');
        $this->addSql('CREATE INDEX IDX_53DE51E732C8A3DE ON registrations (organization_id)');
        $this->addSql('COMMENT ON COLUMN registrations.uuid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE organizations_members (id BIGINT NOT NULL, member_id BIGINT NOT NULL, organization_id BIGINT NOT NULL, is_admin BOOLEAN NOT NULL, projects_permissions JSON NOT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BA358097D17F50A6 ON organizations_members (uuid)');
        $this->addSql('CREATE INDEX IDX_BA3580977597D3FE ON organizations_members (member_id)');
        $this->addSql('CREATE INDEX IDX_BA35809732C8A3DE ON organizations_members (organization_id)');
        $this->addSql('COMMENT ON COLUMN organizations_members.uuid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE areas (id BIGINT NOT NULL, parent_id BIGINT DEFAULT NULL, tree_root BIGINT DEFAULT NULL, type VARCHAR(10) NOT NULL, code VARCHAR(40) NOT NULL, name VARCHAR(100) NOT NULL, description VARCHAR(100) DEFAULT NULL, tree_level SMALLINT NOT NULL, tree_left INT NOT NULL, tree_right INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_58B0B25C77153098 ON areas (code)');
        $this->addSql('CREATE INDEX IDX_58B0B25C727ACA70 ON areas (parent_id)');
        $this->addSql('CREATE INDEX IDX_58B0B25CA977936C ON areas (tree_root)');
        $this->addSql('CREATE TABLE domains (id BIGINT NOT NULL, organization_id BIGINT DEFAULT NULL, zone_id VARCHAR(75) DEFAULT NULL, name VARCHAR(150) NOT NULL, status VARCHAR(30) NOT NULL, config JSON NOT NULL, last_checked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8C7BBF9D5E237E06 ON domains (name)');
        $this->addSql('CREATE INDEX IDX_8C7BBF9D32C8A3DE ON domains (organization_id)');
        $this->addSql('CREATE TABLE organizations (id BIGINT NOT NULL, name VARCHAR(60) NOT NULL, stripe_customer_id VARCHAR(50) DEFAULT NULL, stripe_subscription_id VARCHAR(50) DEFAULT NULL, active BOOLEAN NOT NULL, trialing BOOLEAN NOT NULL, current_period_end TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, projects_slots INT NOT NULL, credits_balance BIGINT NOT NULL, contacts_flags_labels JSON NOT NULL, contacts_flags_is_progress BOOLEAN NOT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_427C1C7FD17F50A6 ON organizations (uuid)');
        $this->addSql('CREATE INDEX stripe_customer_id_idx ON organizations (stripe_customer_id)');
        $this->addSql('CREATE INDEX stripe_subscription_id_idx ON organizations (stripe_subscription_id)');
        $this->addSql('COMMENT ON COLUMN organizations.uuid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE uploads (id BIGINT NOT NULL, project_id BIGINT DEFAULT NULL, pathname VARCHAR(250) NOT NULL, last_accessed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_96117F18A225DBE9 ON uploads (pathname)');
        $this->addSql('CREATE INDEX IDX_96117F18166D1F9C ON uploads (project_id)');
        $this->addSql('CREATE TABLE community_tags (id BIGINT NOT NULL, organization_id BIGINT NOT NULL, name VARCHAR(50) NOT NULL, slug VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AEED7EEC32C8A3DE ON community_tags (organization_id)');
        $this->addSql('CREATE INDEX community_tags_slug_idx ON community_tags (slug)');
        $this->addSql('CREATE TABLE community_contacts_tags (tag_id BIGINT NOT NULL, contact_id BIGINT NOT NULL, PRIMARY KEY(tag_id, contact_id))');
        $this->addSql('CREATE INDEX IDX_F32AE12BAD26311 ON community_contacts_tags (tag_id)');
        $this->addSql('CREATE INDEX IDX_F32AE12E7A1254A ON community_contacts_tags (contact_id)');
        $this->addSql('CREATE TABLE community_emailing_campaigns (id BIGINT NOT NULL, project_id BIGINT NOT NULL, subject VARCHAR(150) NOT NULL, preview VARCHAR(150) DEFAULT NULL, from_email VARCHAR(250) NOT NULL, from_name VARCHAR(150) DEFAULT NULL, track_opens BOOLEAN NOT NULL, track_clicks BOOLEAN NOT NULL, content TEXT DEFAULT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, resolved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3F712D4CD17F50A6 ON community_emailing_campaigns (uuid)');
        $this->addSql('CREATE INDEX IDX_3F712D4C166D1F9C ON community_emailing_campaigns (project_id)');
        $this->addSql('COMMENT ON COLUMN community_emailing_campaigns.uuid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE community_emailing_campaigns_areas_filter (emailing_campaign_id BIGINT NOT NULL, area_id BIGINT NOT NULL, PRIMARY KEY(emailing_campaign_id, area_id))');
        $this->addSql('CREATE INDEX IDX_765862138E9567 ON community_emailing_campaigns_areas_filter (emailing_campaign_id)');
        $this->addSql('CREATE INDEX IDX_76586213BD0F409C ON community_emailing_campaigns_areas_filter (area_id)');
        $this->addSql('CREATE TABLE community_emailing_campaigns_tags_filter (emailing_campaign_id BIGINT NOT NULL, tag_id BIGINT NOT NULL, PRIMARY KEY(emailing_campaign_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_D4C089D78E9567 ON community_emailing_campaigns_tags_filter (emailing_campaign_id)');
        $this->addSql('CREATE INDEX IDX_D4C089D7BAD26311 ON community_emailing_campaigns_tags_filter (tag_id)');
        $this->addSql('CREATE TABLE community_emailing_campaigns_messages (id BIGINT NOT NULL, campaign_id BIGINT NOT NULL, contact_id BIGINT NOT NULL, sent BOOLEAN NOT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, opened BOOLEAN NOT NULL, opened_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, clicked BOOLEAN NOT NULL, clicked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, unsubscribed BOOLEAN NOT NULL, unsubscribed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, bounced BOOLEAN NOT NULL, bounced_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, marked_spam BOOLEAN NOT NULL, marked_spam_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1024B285F639F774 ON community_emailing_campaigns_messages (campaign_id)');
        $this->addSql('CREATE INDEX IDX_1024B285E7A1254A ON community_emailing_campaigns_messages (contact_id)');
        $this->addSql('CREATE TABLE community_contacts (id BIGINT NOT NULL, organization_id BIGINT NOT NULL, area_id BIGINT DEFAULT NULL, address_country_id BIGINT DEFAULT NULL, email VARCHAR(250) NOT NULL, profile_formal_title VARCHAR(20) DEFAULT NULL, profile_first_name VARCHAR(150) DEFAULT NULL, profile_middle_name VARCHAR(150) DEFAULT NULL, profile_last_name VARCHAR(150) DEFAULT NULL, profile_birthdate DATE DEFAULT NULL, profile_company VARCHAR(150) DEFAULT NULL, profile_job_title VARCHAR(150) DEFAULT NULL, account_password VARCHAR(250) DEFAULT NULL, account_language VARCHAR(10) DEFAULT NULL, contact_additional_emails JSON NOT NULL, contact_phone VARCHAR(50) DEFAULT NULL, contact_work_phone VARCHAR(50) DEFAULT NULL, social_facebook VARCHAR(150) DEFAULT NULL, social_twitter VARCHAR(150) DEFAULT NULL, social_linked_in VARCHAR(150) DEFAULT NULL, social_telegram VARCHAR(150) DEFAULT NULL, social_whatsapp VARCHAR(150) DEFAULT NULL, address_street_line1 VARCHAR(150) DEFAULT NULL, address_street_line2 VARCHAR(150) DEFAULT NULL, address_zip_code VARCHAR(150) DEFAULT NULL, address_city VARCHAR(150) DEFAULT NULL, settings_receive_newsletters BOOLEAN NOT NULL, settings_receive_events BOOLEAN NOT NULL, settings_unsubscribe_all BOOLEAN NOT NULL, metadata_flags JSON NOT NULL, metadata_custom_fields JSON NOT NULL, metadata_source VARCHAR(50) DEFAULT NULL, metadata_comment VARCHAR(250) DEFAULT NULL, internal_last_logged_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, internal_email_confirmed BOOLEAN NOT NULL, internal_email_bounced BOOLEAN NOT NULL, internal_token VARCHAR(64) DEFAULT NULL, internal_registration_uuid UUID DEFAULT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C106D054D17F50A6 ON community_contacts (uuid)');
        $this->addSql('CREATE INDEX IDX_C106D05432C8A3DE ON community_contacts (organization_id)');
        $this->addSql('CREATE INDEX IDX_C106D054BD0F409C ON community_contacts (area_id)');
        $this->addSql('CREATE INDEX IDX_C106D05481B2B6EE ON community_contacts (address_country_id)');
        $this->addSql('CREATE INDEX community_contacts_email_idx ON community_contacts (email)');
        $this->addSql('COMMENT ON COLUMN community_contacts.internal_registration_uuid IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN community_contacts.uuid IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE subscriptions_logs ADD CONSTRAINT FK_27FC727932C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE projects ADD CONSTRAINT FK_5C93B3A432C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE projects ADD CONSTRAINT FK_5C93B3A4584D14C2 FOREIGN KEY (root_domain_id) REFERENCES domains (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE projects ADD CONSTRAINT FK_5C93B3A459FBCC09 FOREIGN KEY (appearance_logo_dark_id) REFERENCES uploads (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE projects ADD CONSTRAINT FK_5C93B3A478B771E FOREIGN KEY (appearance_logo_white_id) REFERENCES uploads (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE projects ADD CONSTRAINT FK_5C93B3A4B6319F89 FOREIGN KEY (appearance_icon_id) REFERENCES uploads (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE projects_areas ADD CONSTRAINT FK_CD31E662166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE projects_areas ADD CONSTRAINT FK_CD31E662BD0F409C FOREIGN KEY (area_id) REFERENCES areas (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE website_posts ADD CONSTRAINT FK_DF370A363DA5256D FOREIGN KEY (image_id) REFERENCES uploads (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE website_posts ADD CONSTRAINT FK_DF370A36166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE website_posts_posts_categories ADD CONSTRAINT FK_CE3D47134B89032C FOREIGN KEY (post_id) REFERENCES website_posts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE website_posts_posts_categories ADD CONSTRAINT FK_CE3D4713FE0617CD FOREIGN KEY (post_category_id) REFERENCES website_posts_categories (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE website_pages_categories ADD CONSTRAINT FK_E0D4BA70166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE website_pages ADD CONSTRAINT FK_771E55B93DA5256D FOREIGN KEY (image_id) REFERENCES uploads (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE website_pages ADD CONSTRAINT FK_771E55B9166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE website_pages_pages_categories ADD CONSTRAINT FK_8C8564D0C4663E4 FOREIGN KEY (page_id) REFERENCES website_pages (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE website_pages_pages_categories ADD CONSTRAINT FK_8C8564D05FAC390 FOREIGN KEY (page_category_id) REFERENCES website_pages_categories (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE website_posts_categories ADD CONSTRAINT FK_1B286E2D166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE website_documents ADD CONSTRAINT FK_31689A5C93CB796C FOREIGN KEY (file_id) REFERENCES uploads (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE website_documents ADD CONSTRAINT FK_31689A5C166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE registrations ADD CONSTRAINT FK_53DE51E732C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE organizations_members ADD CONSTRAINT FK_BA3580977597D3FE FOREIGN KEY (member_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE organizations_members ADD CONSTRAINT FK_BA35809732C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE areas ADD CONSTRAINT FK_58B0B25C727ACA70 FOREIGN KEY (parent_id) REFERENCES areas (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE areas ADD CONSTRAINT FK_58B0B25CA977936C FOREIGN KEY (tree_root) REFERENCES areas (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domains ADD CONSTRAINT FK_8C7BBF9D32C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE uploads ADD CONSTRAINT FK_96117F18166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE community_tags ADD CONSTRAINT FK_AEED7EEC32C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE community_contacts_tags ADD CONSTRAINT FK_F32AE12BAD26311 FOREIGN KEY (tag_id) REFERENCES community_tags (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE community_contacts_tags ADD CONSTRAINT FK_F32AE12E7A1254A FOREIGN KEY (contact_id) REFERENCES community_contacts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE community_emailing_campaigns ADD CONSTRAINT FK_3F712D4C166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE community_emailing_campaigns_areas_filter ADD CONSTRAINT FK_765862138E9567 FOREIGN KEY (emailing_campaign_id) REFERENCES community_emailing_campaigns (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE community_emailing_campaigns_areas_filter ADD CONSTRAINT FK_76586213BD0F409C FOREIGN KEY (area_id) REFERENCES areas (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE community_emailing_campaigns_tags_filter ADD CONSTRAINT FK_D4C089D78E9567 FOREIGN KEY (emailing_campaign_id) REFERENCES community_emailing_campaigns (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE community_emailing_campaigns_tags_filter ADD CONSTRAINT FK_D4C089D7BAD26311 FOREIGN KEY (tag_id) REFERENCES community_tags (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE community_emailing_campaigns_messages ADD CONSTRAINT FK_1024B285F639F774 FOREIGN KEY (campaign_id) REFERENCES community_emailing_campaigns (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE community_emailing_campaigns_messages ADD CONSTRAINT FK_1024B285E7A1254A FOREIGN KEY (contact_id) REFERENCES community_contacts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE community_contacts ADD CONSTRAINT FK_C106D05432C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE community_contacts ADD CONSTRAINT FK_C106D054BD0F409C FOREIGN KEY (area_id) REFERENCES areas (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE community_contacts ADD CONSTRAINT FK_C106D05481B2B6EE FOREIGN KEY (address_country_id) REFERENCES areas (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        // Initial required data
        $this->addSql('INSERT INTO domains (id, organization_id, zone_id, name, status, config, last_checked_at) VALUES (nextval(\'domains_id_seq\'), NULL, \'f1e3ecfee818efa21298523fd85c561d\', \'c4o.io\', \'configured\', \'[]\', CURRENT_TIMESTAMP)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE organizations_members DROP CONSTRAINT FK_BA3580977597D3FE');
        $this->addSql('ALTER TABLE projects_areas DROP CONSTRAINT FK_CD31E662166D1F9C');
        $this->addSql('ALTER TABLE website_posts DROP CONSTRAINT FK_DF370A36166D1F9C');
        $this->addSql('ALTER TABLE website_pages_categories DROP CONSTRAINT FK_E0D4BA70166D1F9C');
        $this->addSql('ALTER TABLE website_pages DROP CONSTRAINT FK_771E55B9166D1F9C');
        $this->addSql('ALTER TABLE website_posts_categories DROP CONSTRAINT FK_1B286E2D166D1F9C');
        $this->addSql('ALTER TABLE website_documents DROP CONSTRAINT FK_31689A5C166D1F9C');
        $this->addSql('ALTER TABLE uploads DROP CONSTRAINT FK_96117F18166D1F9C');
        $this->addSql('ALTER TABLE community_emailing_campaigns DROP CONSTRAINT FK_3F712D4C166D1F9C');
        $this->addSql('ALTER TABLE website_posts_posts_categories DROP CONSTRAINT FK_CE3D47134B89032C');
        $this->addSql('ALTER TABLE website_pages_pages_categories DROP CONSTRAINT FK_8C8564D05FAC390');
        $this->addSql('ALTER TABLE website_pages_pages_categories DROP CONSTRAINT FK_8C8564D0C4663E4');
        $this->addSql('ALTER TABLE website_posts_posts_categories DROP CONSTRAINT FK_CE3D4713FE0617CD');
        $this->addSql('ALTER TABLE projects_areas DROP CONSTRAINT FK_CD31E662BD0F409C');
        $this->addSql('ALTER TABLE areas DROP CONSTRAINT FK_58B0B25C727ACA70');
        $this->addSql('ALTER TABLE areas DROP CONSTRAINT FK_58B0B25CA977936C');
        $this->addSql('ALTER TABLE community_emailing_campaigns_areas_filter DROP CONSTRAINT FK_76586213BD0F409C');
        $this->addSql('ALTER TABLE community_contacts DROP CONSTRAINT FK_C106D054BD0F409C');
        $this->addSql('ALTER TABLE community_contacts DROP CONSTRAINT FK_C106D05481B2B6EE');
        $this->addSql('ALTER TABLE projects DROP CONSTRAINT FK_5C93B3A4584D14C2');
        $this->addSql('ALTER TABLE subscriptions_logs DROP CONSTRAINT FK_27FC727932C8A3DE');
        $this->addSql('ALTER TABLE projects DROP CONSTRAINT FK_5C93B3A432C8A3DE');
        $this->addSql('ALTER TABLE registrations DROP CONSTRAINT FK_53DE51E732C8A3DE');
        $this->addSql('ALTER TABLE organizations_members DROP CONSTRAINT FK_BA35809732C8A3DE');
        $this->addSql('ALTER TABLE domains DROP CONSTRAINT FK_8C7BBF9D32C8A3DE');
        $this->addSql('ALTER TABLE community_tags DROP CONSTRAINT FK_AEED7EEC32C8A3DE');
        $this->addSql('ALTER TABLE community_contacts DROP CONSTRAINT FK_C106D05432C8A3DE');
        $this->addSql('ALTER TABLE projects DROP CONSTRAINT FK_5C93B3A459FBCC09');
        $this->addSql('ALTER TABLE projects DROP CONSTRAINT FK_5C93B3A478B771E');
        $this->addSql('ALTER TABLE projects DROP CONSTRAINT FK_5C93B3A4B6319F89');
        $this->addSql('ALTER TABLE website_posts DROP CONSTRAINT FK_DF370A363DA5256D');
        $this->addSql('ALTER TABLE website_pages DROP CONSTRAINT FK_771E55B93DA5256D');
        $this->addSql('ALTER TABLE website_documents DROP CONSTRAINT FK_31689A5C93CB796C');
        $this->addSql('ALTER TABLE community_contacts_tags DROP CONSTRAINT FK_F32AE12BAD26311');
        $this->addSql('ALTER TABLE community_emailing_campaigns_tags_filter DROP CONSTRAINT FK_D4C089D7BAD26311');
        $this->addSql('ALTER TABLE community_emailing_campaigns_areas_filter DROP CONSTRAINT FK_765862138E9567');
        $this->addSql('ALTER TABLE community_emailing_campaigns_tags_filter DROP CONSTRAINT FK_D4C089D78E9567');
        $this->addSql('ALTER TABLE community_emailing_campaigns_messages DROP CONSTRAINT FK_1024B285F639F774');
        $this->addSql('ALTER TABLE community_contacts_tags DROP CONSTRAINT FK_F32AE12E7A1254A');
        $this->addSql('ALTER TABLE community_emailing_campaigns_messages DROP CONSTRAINT FK_1024B285E7A1254A');
        $this->addSql('DROP SEQUENCE subscriptions_logs_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE users_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE projects_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE website_posts_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE website_pages_categories_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE website_pages_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE website_posts_categories_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE website_documents_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE registrations_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE organizations_members_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE domains_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE organizations_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE uploads_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE community_tags_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE community_emailing_campaigns_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE community_emailing_campaigns_messages_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE community_contacts_id_seq CASCADE');
        $this->addSql('DROP TABLE subscriptions_logs');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE projects');
        $this->addSql('DROP TABLE projects_areas');
        $this->addSql('DROP TABLE website_posts');
        $this->addSql('DROP TABLE website_posts_posts_categories');
        $this->addSql('DROP TABLE website_pages_categories');
        $this->addSql('DROP TABLE website_pages');
        $this->addSql('DROP TABLE website_pages_pages_categories');
        $this->addSql('DROP TABLE website_posts_categories');
        $this->addSql('DROP TABLE website_documents');
        $this->addSql('DROP TABLE registrations');
        $this->addSql('DROP TABLE organizations_members');
        $this->addSql('DROP TABLE areas');
        $this->addSql('DROP TABLE domains');
        $this->addSql('DROP TABLE organizations');
        $this->addSql('DROP TABLE uploads');
        $this->addSql('DROP TABLE community_tags');
        $this->addSql('DROP TABLE community_contacts_tags');
        $this->addSql('DROP TABLE community_emailing_campaigns');
        $this->addSql('DROP TABLE community_emailing_campaigns_areas_filter');
        $this->addSql('DROP TABLE community_emailing_campaigns_tags_filter');
        $this->addSql('DROP TABLE community_emailing_campaigns_messages');
        $this->addSql('DROP TABLE community_contacts');
    }
}
