parameters:
    analytics_database_url: '%env(resolve:DATABASE_URL)%'

services:
    _defaults:
        autowire: true
        public: true

    #
    # Security
    #
    Scheb\TwoFactorBundle\Security\TwoFactor\Provider\Totp\TotpAuthenticatorInterface:
        class: 'App\Tests\Stubs\TotpAuthenticatorStub'

    #
    # Bridges
    #
    App\Bridge\Cloudflare\CloudflareInterface:
        class: 'App\Bridge\Cloudflare\MockCloudflare'

    App\Bridge\Sendgrid\SendgridInterface:
        class: 'App\Bridge\Sendgrid\MockSendgrid'

    App\Bridge\Postmark\PostmarkInterface:
        class: 'App\Bridge\Postmark\MockPostmark'

    App\Bridge\Twilio\TwilioInterface:
        class: 'App\Bridge\Twilio\MockTwilio'

    App\Bridge\Revue\RevueInterface:
        class: 'App\Bridge\Revue\MockRevue'

    App\Bridge\Github\GithubInterface:
        class: 'App\Bridge\Github\MockGithub'

    App\Bridge\Mollie\MollieInterface:
        class: 'App\Bridge\Mollie\MockMollie'

    App\Bridge\Uploadcare\UploadcareInterface:
        class: 'App\Bridge\Uploadcare\MockUploadcare'

    #
    # Override Mollie Connect for tests to avoid network
    #
#    App\Bridge\Mollie\MollieConnectInterface:
#        class: 'App\Bridge\Mollie\MockMollieConnect'
#        arguments:
#            $mollieConnectClientId: '%env(MOLLIE_CONNECT_CLIENT_ID)%'
#            $mollieConnectClientSecret: '%env(MOLLIE_CONNECT_CLIENT_SECRET)%'
#            $mollieConnectRedirectUri: '%env(MOLLIE_CONNECT_REDIRECT_URI)%'

    # Expose the persister service for direct retrieval in tests
    App\Community\Payment\MollieTransactionPersister:
        public: true
